spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/events
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
      show_sql: true
      use_sql_comments: true

  messages:
    encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
logging:
  level:
    org:
      hibernate:
        type: trace

